name: pyrfu_ci
channels:
- conda-forge
- defaults
dependencies:
- astropy
- scipy
- pyfftw
- spacepy
- xarray
- sphinxcontrib-apidoc
- sphinx
- ipython
- ipykernel
- sphinx
- sphinx_rtd_theme
- nbsphinx