name: pyrfu_ci
channels:
- conda-forge
- defaults
dependencies:
- astropy
- cycler
- ipykernel
- ipython
- matplotlib
- nbsphinx
- numpy
- pandas
- psychopy
- pyfftw
- scipy
- seaborn
- sphinx
- sphinxcontrib-apidoc
- sphinx_rtd_theme
- tqdm
- xarray
- cdflib